project:
  type: website
  output-dir: docs

website:
  title: "Sam Wilhelm"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: research.qmd
        text: "Research"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

