project:
  type: website
  output-dir: docs

website:
  title: "Sam Wilhelm"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: research.qmd
        text: "Research"
      - href: publications.qmd
        text: "Publications"
      - href: contact.qmd
        text: "Contact"

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

