---
title: "Research"
---

I study plant-pollinator interactions and community assembly in several different systems. My dissertation is focused on Central Tennessee cedar glades, calcareous rock outcroppings that occur in a matrix of deciduous broad leaf and eastern red cedar forests. They are habitat to a unique assemblage of endemic and rare plants, and my research is the first to document the associated bee communities of these plants. My team and I have hand-netted over 3,500 specimens representing 5 families and 100+ species of native bees.

I also examine the effects of controlled burning and other restoration techniques on plant and pollinator communities. I have conducted research in restored tallgrass prairies in Illinois, mixed-grass prairies of Texas and Oklahoma, and shortleaf pine savannas of the central TN hardwoods region. I have also studied bee communities in three ecoregions of New Jersey: the Appalachian Highlands, Piedmont, and Pine Barrens.

Additionally, I have documented bee diversity across the Mid-South in collaboration with a range of taxonomists.

**Funding**

Fall 2024 - Spring 2027 - NSF Graduate Research Fellowship
